In [ ]:
import torch
import numpy as np

# Creating arrays in NumPy
np_array = np.array([1, 2, 3])
print(np_array)

# Creating tensors in PyTorch
torch_tensor = torch.tensor([1, 2, 3])
print(torch_tensor)


[1 2 3]
tensor([1, 2, 3])



Let’s start with dimensions and shapes in the simplest terms and build up from there.

1. What Are Dimensions in Numpy Arrays and PyTorch Tensors?
A dimension represents the number of "directions" or "levels of organization" in your data. It defines how many steps it takes to locate an element.

1D Array or Tensor: A simple list of numbers (like a single line of data).
2D Array or Tensor: A table of numbers with rows and columns (like a spreadsheet).
3D Array or Tensor: A stack of tables, like multiple pages in a book.

The shape of an array or tensor tells you how many elements (data points) exist along each dimension.

In 1D, the shape is just the number of elements.
Example: [1, 2, 3] → Shape: (3,) (3 elements in 1 dimension)
In 2D, the shape is (rows, columns).
Example: A table like [[1, 2], [3, 4]] → Shape: (2, 2) (2 rows, 2 columns)
In 3D, the shape might be (stacks, rows, columns)

In [ ]:
#2 D

# Numpy
np_array = np.array([[1, 2],
                     [3, 4]])  # Shape: (2, 2)

# PyTorch
torch_tensor = torch.tensor([[1, 2],
                             [3, 4]])  # Shape: (2, 2)


In [ ]:
# 3D

# Numpy
np_array = np.array([[[1, 2],
 [3, 4]],
[[5, 6],
 [7, 8]]])  # Shape: (2, 2, 2)

# PyTorch
torch_tensor = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape: (2, 2, 2)


In [ ]:
\3D
Week 1:
[[85, 90, 78],
 [92, 88, 79],
 [80, 84, 88],
 [91, 95, 94],
 [88, 82, 85]]

Week 2:
[[89, 92, 80],
 [94, 91, 82],
 [83, 88, 90],
 [96, 97, 98],
 [87, 85, 88]] → Shape: (2, 5, 3)


What Does torch.unsqueeze Do?
torch.unsqueeze adds a new dimension to the tensor at the specified axis (or position). It doesn’t add new data; it simply changes the way the data is represented. The original values remain unchanged.

In [ ]:
tensor = torch.tensor([1, 2, 3])  # Shape: (3,) new shape  (1, 3) → 1 row and 3 columns.
tensor_unsqueezed = torch.unsqueeze(tensor, dim=0)
print(tensor_unsqueezed)


tensor([[1, 2, 3]])


In [ ]:
#chnaging shapes

tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])  # Shape: (3, 2)

# Reshape into a 2D tensor with 2 rows and 3 columns
reshaped_tensor = tensor.view(2, 3)  # Shape: (2, 3)
print(reshaped_tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Original tensor: shape (2, 3)
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Original tensor:", tensor.shape)  # Shape: (2, 3)

# Reshape to (3, 2)
reshaped_tensor = tensor.view(3, 2)
print("Reshaped to (3, 2):", reshaped_tensor.shape)  # Shape: (3, 2)

# Reshape to (6,) using -1 (automatic calculation)
flattened_tensor = tensor.view(-1)
print("Flattened to (6,):", flattened_tensor.shape)  # Shape: (6,)


In [ ]:
import torch

# Example rewards tensor: shape (4,)
rewards = torch.tensor([10.0, 5.0, 20.0, 15.0])  # Shape: (4,)
threshold = 12.0

def quantilization_sigmoid(rewards, threshold):
    sigma = 1.0  # Smoothness factor

    # Step 1: Subtract threshold, resulting in tensor of same shape (4,)
    adjusted_rewards = rewards - threshold  # Shape: (4,)

    # Step 2: Apply the sigmoid formula element-wise
    scaled_rewards = -(adjusted_rewards / sigma)  # Shape: (4,)
    sigmoid_values = 1 / (1 + torch.exp(scaled_rewards))  # Shape: (4,)

    return sigmoid_values

quantilized_rewards = quantilization_sigmoid(rewards, threshold)
print("Quantilized rewards:", quantilized_rewards)


In [ ]:
# Current rewards shape: (4,)
rewards = torch.tensor([10.0, 5.0, 20.0, 15.0])  # Shape: (4,)

# Add a batch dimension at position 0: shape becomes (1, 4)
batched_rewards = torch.unsqueeze(rewards, dim=0)
print("Batched rewards shape:", batched_rewards.shape)


In [ ]:
# Assume we want the rewards as a 2x2 tensor for some computation
reshaped_rewards = rewards.view(2, 2)
print("Reshaped rewards shape:", reshaped_rewards.shape)
